spring.application.name=goatedmeals



# ===============================
# DATABASE CONNECTION (Supabase)
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.bpypulrofzrcvlslcued
spring.datasource.password=xavier.Fernandez34goatedmeals
spring.datasource.driver-class-name=org.postgresql.Driver

# Supabase Configuration
supabase.url=
supabase.Key=

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# "update" automatically creates/updates your tables based on your Java models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080

# Increase maximum file upload size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Google OAuth Configuration
# Replace this with your actual Client ID from Google Cloud Console later
google.client.id=

# PayMongo Configuration
paymongo.secret.key=
paymongo.api.url=
